### PR TITLE
Add flag for skipping final confirmation

### PR DESCRIPTION
**Pull request by craigomatic**
PR for #56 that implements the feature for both C# and NodeJS, targeting master branch

### CODE REVIEW

**Comment by craigomatic** [comment]
You're right, sorry about that! Not sure how I missed including that in the prior commit :/

**Comment by mbadreldin** [comment]
@craigomatic No worries :)

**Comment by mbadreldin** [comment]
Hey @craigomatic,
I will merge this to master now. In order to keep the branches in sync, could you please make another pull request to the branch 'develop' with the same changes?
Thanks!

**Comment by kgrashad** [comment]
@craigomatic Just to clarify Maha's request. You don't need to create a new branch and add your commits. Just create a pull request from the same branch you have (that was branched of master) to upstream develop.

**Pull request merged**
